/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ST6;

public class App {
    public String getGreeting() {
        System.out.println("My name is Amalie");
        return "Hello world. ";
        System.out.println("My name is Sofie");
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
